# coding: utf-8

"""
    AI Cockpit Decisions

    This API is part of project AI cockpit.   For more details see: https://www.kicockpit.eu/ 

    The version of the OpenAPI document: 0.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Action(BaseModel):
    """
    An actual action that a system executes
    """ # noqa: E501
    id: Optional[StrictInt] = None
    creation_time: Optional[datetime] = Field(default=None, alias="creationTime")
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    decision: Optional[Decision] = None
    action_type: Optional[ActionType] = Field(default=None, alias="actionType")
    metadata: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "creationTime", "name", "description", "decision", "actionType", "metadata"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Action from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of decision
        if self.decision:
            _dict['decision'] = self.decision.to_dict()
        # override the default output from pydantic by calling `to_dict()` of action_type
        if self.action_type:
            _dict['actionType'] = self.action_type.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Action from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "creationTime": obj.get("creationTime"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "decision": Decision.from_dict(obj["decision"]) if obj.get("decision") is not None else None,
            "actionType": ActionType.from_dict(obj["actionType"]) if obj.get("actionType") is not None else None,
            "metadata": obj.get("metadata")
        })
        return _obj

from starwit_aic_api.models.action_type import ActionType
from starwit_aic_api.models.decision import Decision
# TODO: Rewrite to not use raise_errors
Action.model_rebuild(raise_errors=False)

