# coding: utf-8

"""
    AI Cockpit Decisions

    This API is part of project AI cockpit.   For more details see: https://www.kicockpit.eu/ 

    The version of the OpenAPI document: 0.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AIModelType(str, Enum):
    """
    AIModelType
    """

    """
    allowed enum values
    """
    LLM = 'LLM'
    COMPUTERVISION = 'ComputerVision'
    RULEBASED = 'RuleBased'
    MISC = 'Misc'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AIModelType from a JSON string"""
        return cls(json.loads(json_str))


