# coding: utf-8

"""
    AI Cockpit Transparency

    This API is part of project AI cockpit.   For more details see: https://www.kicockpit.eu/ 

    The version of the OpenAPI document: 0.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from starwit_aic_api.models.ai_model import AIModel
from starwit_aic_api.models.module_sbom_location_value import ModuleSBOMLocationValue
from typing import Optional, Set
from typing_extensions import Self

class Module(BaseModel):
    """
    Module
    """ # noqa: E501
    id: Optional[StrictInt] = None
    version: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    application_identifier: Optional[StrictStr] = Field(default=None, alias="applicationIdentifier")
    description: Optional[StrictStr] = None
    use_ai: Optional[StrictBool] = Field(default=None, alias="useAI")
    model: Optional[AIModel] = None
    action_types: Optional[List[ActionType]] = Field(default=None, alias="actionTypes")
    decision_types: Optional[List[DecisionType]] = Field(default=None, alias="decisionTypes")
    s_bom_location: Optional[Dict[str, ModuleSBOMLocationValue]] = Field(default=None, alias="sBOMLocation")
    successors: Optional[List[Module]] = None
    __properties: ClassVar[List[str]] = ["id", "version", "name", "applicationIdentifier", "description", "useAI", "model", "actionTypes", "decisionTypes", "sBOMLocation", "successors"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Module from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of model
        if self.model:
            _dict['model'] = self.model.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in action_types (list)
        _items = []
        if self.action_types:
            for _item_action_types in self.action_types:
                if _item_action_types:
                    _items.append(_item_action_types.to_dict())
            _dict['actionTypes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in decision_types (list)
        _items = []
        if self.decision_types:
            for _item_decision_types in self.decision_types:
                if _item_decision_types:
                    _items.append(_item_decision_types.to_dict())
            _dict['decisionTypes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in s_bom_location (dict)
        _field_dict = {}
        if self.s_bom_location:
            for _key_s_bom_location in self.s_bom_location:
                if self.s_bom_location[_key_s_bom_location]:
                    _field_dict[_key_s_bom_location] = self.s_bom_location[_key_s_bom_location].to_dict()
            _dict['sBOMLocation'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in successors (list)
        _items = []
        if self.successors:
            for _item_successors in self.successors:
                if _item_successors:
                    _items.append(_item_successors.to_dict())
            _dict['successors'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Module from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "version": obj.get("version"),
            "name": obj.get("name"),
            "applicationIdentifier": obj.get("applicationIdentifier"),
            "description": obj.get("description"),
            "useAI": obj.get("useAI"),
            "model": AIModel.from_dict(obj["model"]) if obj.get("model") is not None else None,
            "actionTypes": [ActionType.from_dict(_item) for _item in obj["actionTypes"]] if obj.get("actionTypes") is not None else None,
            "decisionTypes": [DecisionType.from_dict(_item) for _item in obj["decisionTypes"]] if obj.get("decisionTypes") is not None else None,
            "sBOMLocation": dict(
                (_k, ModuleSBOMLocationValue.from_dict(_v))
                for _k, _v in obj["sBOMLocation"].items()
            )
            if obj.get("sBOMLocation") is not None
            else None,
            "successors": [Module.from_dict(_item) for _item in obj["successors"]] if obj.get("successors") is not None else None
        })
        return _obj

from starwit_aic_api.models.action_type import ActionType
from starwit_aic_api.models.decision_type import DecisionType
# TODO: Rewrite to not use raise_errors
Module.model_rebuild(raise_errors=False)

