/*
 * AI Cockpit Decisions
 * This API is part of project AI cockpit.   For more details see: https://www.kicockpit.eu/ 
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.starwit.aic.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets AIModelType
 */
@JsonAdapter(AIModelType.Adapter.class)
public enum AIModelType {
  
  LLM("LLM"),
  
  COMPUTERVISION("ComputerVision"),
  
  RULEBASED("RuleBased"),
  
  MISC("Misc");

  private String value;

  AIModelType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AIModelType fromValue(String value) {
    for (AIModelType b : AIModelType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AIModelType> {
    @Override
    public void write(final JsonWriter jsonWriter, final AIModelType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AIModelType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AIModelType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    AIModelType.fromValue(value);
  }
}

