name: PR Build

# PR build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build-java:
    name: "Build java library"
    runs-on: [self-hosted, linux, X64]
    container:
      image: starwitorg/debian-packaging:0.0.3

    steps:    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
         maven-version: 3.9.2

    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    
    - name: Generate Java lib
      working-directory: ./java
      run: |
        ./generate.sh 

    - name: Try to build Java lib
      working-directory: ./java/aicockpit-jar
      run: | 
        mvn package --settings ${{ github.workspace }}/.github/workflows/settings.xml
        ls -al ./target
      env:
         CI: false
         MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
         MAVEN_GPG_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}

  build-python:
    name: "Build Python"
    runs-on: [self-hosted, linux, X64]

    steps:    
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Set up openapi-generator-cli
      run: |
        npm install @openapitools/openapi-generator-cli -g

    - name: Generate Python lib
      working-directory: ./python
      run: |
        ./generate.sh
    
    - name: Set Python lib version
      working-directory: ./python/generated-library
      run: |
        poetry version ${{ env.RELEASE_VERSION }}

    - name: build wheel
      working-directory: ./python/generated-library
      run: |
        poetry build
        ls ./dist