# coding: utf-8

"""
    AI Cockpit Transparency

    This API is part of project AI cockpit.   For more details see: https://www.kicockpit.eu/ 

    The version of the OpenAPI document: 0.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from starwit_aic_api.models.ai_model_type import AIModelType

class TestAIModelType(unittest.TestCase):
    """AIModelType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAIModelType(self):
        """Test AIModelType"""
        # inst = AIModelType()

if __name__ == '__main__':
    unittest.main()
