# coding: utf-8

"""
    AI Cockpit Decisions

    This API is part of project AI cockpit.   For more details see: https://www.kicockpit.eu/ 

    The version of the OpenAPI document: 0.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from starwit_aic_api.models.model_type import ModelType

class TestModelType(unittest.TestCase):
    """ModelType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelType(self):
        """Test ModelType"""
        # inst = ModelType()

if __name__ == '__main__':
    unittest.main()
