# coding: utf-8

"""
    AI Cockpit Transparency

    This API is part of project AI cockpit.   For more details see: https://www.kicockpit.eu/ 

    The version of the OpenAPI document: 0.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from starwit_aic_api.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_info(self) -> None:
        """Test case for get_info

        """
        pass

    def test_get_module(self) -> None:
        """Test case for get_module

        """
        pass

    def test_get_modules(self) -> None:
        """Test case for get_modules

        """
        pass

    def test_register_module(self) -> None:
        """Test case for register_module

        """
        pass

    def test_update_module(self) -> None:
        """Test case for update_module

        """
        pass


if __name__ == '__main__':
    unittest.main()
