# coding: utf-8

"""
    AI Cockpit Decisions

    This API is part of project AI cockpit.   For more details see: https://www.kicockpit.eu/ 

    The version of the OpenAPI document: 0.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from starwit_aic_api.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_decision(self) -> None:
        """Test case for create_decision

        Create decision
        """
        pass

    def test_get_actions_by_id(self) -> None:
        """Test case for get_actions_by_id

        Get action by id
        """
        pass

    def test_get_all_actions(self) -> None:
        """Test case for get_all_actions

        Get all actions
        """
        pass

    def test_get_all_decisions(self) -> None:
        """Test case for get_all_decisions

        Get all decisions
        """
        pass

    def test_get_decisions_by_id(self) -> None:
        """Test case for get_decisions_by_id

        Get decisions by id
        """
        pass

    def test_get_info(self) -> None:
        """Test case for get_info

        """
        pass

    def test_save3(self) -> None:
        """Test case for save3

        Create action
        """
        pass


if __name__ == '__main__':
    unittest.main()
